# U10-V5 METHANE SENSOR CONSTANTS
# DO NOT MODIFY WITHOUT VALIDATION

SAMPLING_RATE_HZ = 40

REFERENCE_AGL_M = 80
WORST_CASE_AGL_M = 95

FOOTPRINT_AT_100M_M = 1.0
FOOTPRINT_WORST_CASE_M = FOOTPRINT_AT_100M_M * (WORST_CASE_AGL_M / 100.0)

SIDELAP = 0.40

PREFERRED_SPEED_MPH = 30
MAX_SPEED_MPH = 35

MIN_END_EXTENSION_FT = 33
